### ISSUE TITLE
dependency versions

### ISSUE THREAD

**Issue by BlasiusVonSzerencsi** [emartech/escher-lua#4]
Please lock dependency versions, as an update of them could break the lib.

Please lock rapidjson to version 0.4.5-1, as it already has a breaking change.

**Comment by felin-arch** [comment]
Acknowledged! Thanks for reporting this!

**Comment by BlasiusVonSzerencsi** [comment]
Hi!

The following versions would be preferred:

luafilesystem -> 1.6.3-2
rapidjson -> 0.4.5-1
luacrypto -> 0.3.2-2
date -> 2.1.1-1

Thanks!

**Comment by jzsfkzm** [comment]
The change is in, build was successful. All we need is a deploy now. Can you check it, @boogie?
